[project]
name = "oem"
description = "Python Orbit Ephemeris Message (OEM) tools"
version = "0.4.5"
authors = [
    { name = "Brad Sease", email = "contact@bradsease.com" }
]
readme = "README.md"
license = {text = "MIT"}

classifiers = [
    "Development Status :: 4 - Beta",
    'Programming Language :: Python',
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

requires-python = ">=3.8"

dependencies = [
    "numpy>=1.20",
    "astropy>=5.0.8",
    "lxml>=4.5.0",
    "defusedxml>=0.6.0",
]

[project.urls]
Homepage = "https://github.com/bradsease/oem"
Repository = "https://github.com/bradsease/oem"
Documentation = "https://github.com/bradsease/oem/tree/main/docs"
Issues = "https://github.com/bradsease/oem/issues"
Changelog = "https://github.com/bradsease/oem/releases"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-benchmark",
    "flake8",
    "black",
]

type = [
    "mypy==1.12.1",
]

coverage = [
    "pytest-cov",
    "coveralls",
]

tle = [
    "sgp4>=2.1"
]

[tool.setuptools.packages.find]
include = ["oem*"]

[tool.setuptools.package-data]
oem = ["py.typed"]

[tool.black]
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
files = ["oem"]
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
follow_imports = "skip"
follow_imports_for_stubs = true
ignore_missing_imports = true
